[workspace]
members = ["crates/git"]

[workspace.package]
edition = "2018"
version = "0.3.1-alpha.1"
authors = ["Aurélien Gâteau <mail@agateau.com>"]

[workspace.dependencies]
chrono = { version = "0.4.43", default-features = false, features = [
    "now"
] }
thiserror = "2.0.17"
log = "0.4.29"

[package]
name = "git-bonsai"
description = "Command-line tool to clean the branches of your git garden"
documentation = "https://github.com/agateau/git-bonsai"
readme = "README.md"
homepage = "https://github.com/agateau/git-bonsai"
repository = "https://github.com/agateau/git-bonsai"
license = "GPL-3.0+"
keywords = ["git", "clean"]
categories = ["command-line-utilities", "development-tools"]
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
thiserror.workspace = true
log.workspace = true
git = { path = "crates/git" }
crossterm = "0.29.0"
ratatui = "0.30.0"
derive_setters = "0.1.8"
regex = "1.12.2"
simplelog = "0.12.2"
clap = { version = "4.6.0", features = ["derive"] }

[dev-dependencies]
assert_fs = "1.0.7"
predicates = "2.1.1"
claim = "0.5.0"
yare = "3.0.0"
