#!/usr/bin/env bash
set -euo pipefail

INIT_BRANCH=main

create_branch() {
    local base=$1
    local branch=$2
    git checkout -b $branch $base
    touch $branch
    git add $branch
    git commit $branch -m "Create $branch"
}

merge() {
    local branch=$1
    git merge --no-ff "$branch" -m "Merging $branch"
}

rm -rf demo
mkdir demo
cd demo

git init --initial-branch=$INIT_BRANCH
touch README
git add README
git commit -m "Init" README

create_branch $INIT_BRANCH topic1
create_branch topic1 topic1-1
create_branch $INIT_BRANCH topic2

git checkout topic1
merge topic1-1

git checkout $INIT_BRANCH
merge topic1

# Create two branches pointing to the same commit
create_branch $INIT_BRANCH duplicate1
git branch duplicate2
git checkout $INIT_BRANCH
