name: Rust

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - '**'

jobs:
  build:
    runs-on:
    - ubuntu-latest
    - macos-latest
    - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
