name: Rust

on:
  push:
    branches:
    - master
    - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ci/build-app
    - name: Run tests
      run: ci/run-tests
